events {}

http {
  upstream livestock_service {
    server livestock-service:3001;
  }

  upstream traceability_service {
    server traceability-service:3002;
  }

  upstream rfid_adapter {
    server rfid-adapter:3003;
  }

  server {
    listen 8080;

    location /api/v1/livestock/ {
      proxy_pass http://livestock_service;
    }

    location /api/v1/traceability/ {
      proxy_pass http://traceability_service;
    }

    location /vendor/rfid/events {
      proxy_pass http://rfid_adapter;
    }
  }
}
